### ISSUE TITLE
Publish consistent Proxy metrics

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/prometheus-rsocket-proxy#92]

**Comment by shakuzen** [comment]
As we discussed offline, I wonder if we shouldn't go the route of removing `publishPercentileHistogram()` from all of them instead. If users can configure that if they want it, I don't see the reason why we would enable it by default other than backward compatibility, but since this is in a new major we can change that.

**Comment by jonatan-ivanov** [comment]
Done in https://github.com/micrometer-metrics/prometheus-rsocket-proxy/issues/93
